apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secretmaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secretmaker
subjects:
- kind: ServiceAccount
  name: secretmaker
  namespace: default
